name: 'testing, building'

on:
  push:
    branches:
      [ dev ]
  pull_request:
    branches:
      [ dev, release/** ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm ci

      - name: build production project
        run: npm run build:prod
        if: always()

      - name: linting code
        run: npm run lint
        if: always()

        run-name: start unit testing # имя запускаемое
      - name: unit testing
        run: npm run test:unit
        if: always() # если проверка выше упадет, это проверка запустится в любом случае

      - name: storybook testing
        run: npm run storybook:build
        if: always()
